// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 单条识曲候选(字段名与酷狗指纹接口对齐,经别名兜底后为非空缺省)。
class IdentifyCandidate {
  final String name;
  final String singer;

  /// 可播放主 hash(128k)
  final String hash;
  final String albumAudioId;
  final String albumId;
  final String albumName;
  final String cover;
  final PlatformInt64 durationMs;

  /// 匹配距离(0~1,越小越准)
  final double dist;
  final String hash320;
  final String hashFlac;

  const IdentifyCandidate({
    required this.name,
    required this.singer,
    required this.hash,
    required this.albumAudioId,
    required this.albumId,
    required this.albumName,
    required this.cover,
    required this.durationMs,
    required this.dist,
    required this.hash320,
    required this.hashFlac,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      singer.hashCode ^
      hash.hashCode ^
      albumAudioId.hashCode ^
      albumId.hashCode ^
      albumName.hashCode ^
      cover.hashCode ^
      durationMs.hashCode ^
      dist.hashCode ^
      hash320.hashCode ^
      hashFlac.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentifyCandidate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          singer == other.singer &&
          hash == other.hash &&
          albumAudioId == other.albumAudioId &&
          albumId == other.albumId &&
          albumName == other.albumName &&
          cover == other.cover &&
          durationMs == other.durationMs &&
          dist == other.dist &&
          hash320 == other.hash320 &&
          hashFlac == other.hashFlac;
}
