// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 扫描结果条目（Dart 侧转 Song 模型）。
class LocalSongEntry {
  final String path;

  /// 标签缺失时为空串，由 Dart 侧回退"文件名猜标题"。
  final String title;
  final String artist;
  final String album;

  /// 时长（毫秒）；probe 拿不到时为 0。
  final PlatformInt64 durationMs;

  const LocalSongEntry({
    required this.path,
    required this.title,
    required this.artist,
    required this.album,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSongEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs;
}
