// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 分析进度/结果事件（Dart 侧 Stream 元素）。
class LoudnessProgress {
  /// 截至当前的 integrated LUFS。
  final double lufs;

  /// 已解码音频时长（毫秒）。
  final PlatformInt64 analyzedMs;

  /// true = 全曲分析完成的最终值（Dart 侧据此写缓存）。
  final bool isFinal;

  const LoudnessProgress({
    required this.lufs,
    required this.analyzedMs,
    required this.isFinal,
  });

  @override
  int get hashCode => lufs.hashCode ^ analyzedMs.hashCode ^ isFinal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoudnessProgress &&
          runtimeType == other.runtimeType &&
          lufs == other.lufs &&
          analyzedMs == other.analyzedMs &&
          isFinal == other.isFinal;
}

/// 分析结果。
class LoudnessResult {
  final double lufs;
  final int sampleRate;
  final PlatformInt64 analyzedMs;

  const LoudnessResult({
    required this.lufs,
    required this.sampleRate,
    required this.analyzedMs,
  });

  @override
  int get hashCode => lufs.hashCode ^ sampleRate.hashCode ^ analyzedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoudnessResult &&
          runtimeType == other.runtimeType &&
          lufs == other.lufs &&
          sampleRate == other.sampleRate &&
          analyzedMs == other.analyzedMs;
}
